name: Update Kubernetes deployment on Docker Hub push

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_REPO: <nazwa_repozytorium>
  K8S_DEPLOYMENT_NAME: nginx-deployment
  K8S_NAMESPACE: test_namespace
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  update-k8s-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t $DOCKER_HUB_REPO:latest .
      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_HUB_REPO:latest
      - name: Update Kubernetes deployment
        uses: Azure/k8s-deploy@v1.1.0
        with:
          manifests: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: ${{ env.K8S_DEPLOYMENT_NAME }}
              namespace: ${{ env.K8S_NAMESPACE }}
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                    - name: nginx-container
                      image: $DOCKER_HUB_REPO:latest
                      ports:
                        - containerPort: 80
