name: Deploy to AKS

on:
  push:
    branches: [main]

env:
  DOCKER_HUB_REPO: ulaania/lab11
  K8S_DEPLOYMENT_NAME: nginx-deployment
  K8S_NAMESPACE: test-namespace

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure kubectl
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: ${{ secrets.KUBE_CONTEXT }}

      - name: Create namespace
        run: kubectl create namespace $K8S_NAMESPACE

      - name: Create Docker secret
        run: |
          kubectl create secret docker-registry docker-hub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=ulaania \
            --docker-password=Lusia12Lusia12 \
            --docker-email=bloom7415@gmail.com \
            --namespace=$K8S_NAMESPACE

      - name: Apply deployment manifest
        run: |
          kubectl apply -f deployment.yaml --namespace=$K8S_NAMESPACE

      - name: Apply service manifest
        run: |
          kubectl apply -f service.yaml --namespace=$K8S_NAMESPACE

      - name: Update deployment image
        run: |
          kubectl set image deployment/$K8S_DEPLOYMENT_NAME \
            $K8S_DEPLOYMENT_NAME=$DOCKER_HUB_REPO:latest \
            --namespace=$K8S_NAMESPACE

      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/$K8S_DEPLOYMENT_NAME \
            --namespace=$K8S_NAMESPACE
